# feature branches

-
  version: '4.1.0.{build}'
  configuration: Release

  branches:
    only:
      - develop
      - /feature\/.*/

  pull_requests:
    do_not_increment_build_number: true

  init:

  nuget:
    project_feed: true

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  before_build:
    - ps: |  
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        Invoke-DisplayBuildInfo
        
        nuget restore Source\NBuilder-NETStandard16.sln
        nuget restore Source\NBuilder-NET4.0.sln
        nuget restore Source\NBuilder-NET3.5.sln

  build_script:
    - ps: |
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        "NET3.5", "NET4.0", "NETStandard16" | Invoke-Build -WorkingDirectory $(pwd)
        Invoke-NuGetPack -Version  (Get-NuGetPackageVersion -Beta) -NuSpec "$(pwd)\nuget\NBuilder.nuspec" -Destination "$(pwd)"
    
  before_test:

  test:
    assemblies:
      - 'nuget\net35\FizzWare.NBuilder.Tests.dll'
      - 'nuget\net40\FizzWare.NBuilder.Tests.dll'
      - 'nuget\net46\FizzWare.NBuilder.Tests.dll'

      - 'nuget\net35\FizzWare.NBuilder.FunctionalTests*.dll'
      - 'nuget\net40\FizzWare.NBuilder.FunctionalTests*.dll'
      - 'nuget\net46\FizzWare.NBuilder.FunctionalTests*.dll'

  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  cache:
    - packages -> **\packages.config




# release branches
# compile, test, release beta version to nuget
-
  version: '4.0.0.{build}'
  configuration: Release

  branches:
    only:
      - /release\/.*/

  pull_requests:
    do_not_increment_build_number: true

  nuget:
    project_feed: true

  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  deploy:
    provider: NuGet
    api_key:
      secure: rEqnyErKFkhgxjUgir8i3zftWJ6AqqzYn/wXPXVSTJo1o9nQML8KU3pmG3sXOqCU
    artifact: nuget-package

  before_build:
    - ps: |  
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        Invoke-DisplayBuildInfo

        nuget restore Source\NBuilder-NET4.0.sln
        nuget restore Source\NBuilder-NET3.5.sln

  build_script:
    - ps: |
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        "NET3.5", "NET4.0" | Invoke-Build -WorkingDirectory $(pwd)
        Invoke-NuGetPack -Version  (Get-NuGetPackageVersion -Beta) -NuSpec "$(pwd)\nuget\NBuilder.nuspec" -Destination "$(pwd)"
    
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  test:
    assemblies:
      - 'nuget\net40\FizzWare.NBuilder.Tests.dll'
      - 'nuget\net40\FizzWare.NBuilder.FunctionalTests*.dll'
      - 'nuget\sl5\FizzWare.NBuilder-Silverlight-4.Tests.dll'

  cache:
    - packages -> **\packages.config


# release branches
# compile, test, release beta version to nuget
-
  version: '4.0.0.{build}'
  configuration: Release

  branches:
    only:
      - master

  pull_requests:
    do_not_increment_build_number: true

  nuget:
    project_feed: true

  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  deploy:
    provider: NuGet
    api_key:
      secure: rEqnyErKFkhgxjUgir8i3zftWJ6AqqzYn/wXPXVSTJo1o9nQML8KU3pmG3sXOqCU
    artifact: nuget-package



  before_build:
    - ps: |  
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        Invoke-DisplayBuildInfo

        nuget restore Source\NBuilder-NET4.0.sln
        nuget restore Source\NBuilder-NET3.5.sln

  build_script:
    - ps: |
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        "NET3.5", "NET4.0" | Invoke-Build -WorkingDirectory $(pwd)
        Invoke-NuGetPack -Version  (Get-NuGetPackageVersion) -NuSpec "$(pwd)\nuget\NBuilder.nuspec" -Destination "$(pwd)"
    
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  test:
    assemblies:
      - 'nuget\net40\FizzWare.NBuilder.Tests.dll'
      - 'nuget\net40\FizzWare.NBuilder.FunctionalTests*.dll'
      - 'nuget\sl5\FizzWare.NBuilder-Silverlight-4.Tests.dll'

  cache:
    - packages -> **\packages.config

