# feature branches
-
  version: '6.0.0.{build}'
  configuration: Release

  branches:
    only:
      - develop
      - /feature\/.*/

  pull_requests:
    do_not_increment_build_number: true

  init:

  nuget:
    project_feed: true

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  before_build:
    - ps: |  
        . ./build/Write-BuildInfo.ps1
        . ./build/Before-Build.ps1

  build_script:
    - ps: |
        . ./build/Build-Script.ps1
        . ./build/New-NugetPackage.ps1 -Beta
        
  before_test:

  test_script:
    - ps: |
        . ./build/Test-Script.ps1

  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  cache:
    - packages -> **\packages.config

# release branches
# compile, test, release beta version to nuget
-
  version: '6.0.0.{build}'
  configuration: Release

  branches:
    only:
      - /release\/.*/

  pull_requests:
    do_not_increment_build_number: true

  nuget:
    project_feed: true

  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  deploy:
    provider: NuGet
    api_key:
      secure: rEqnyErKFkhgxjUgir8i3zftWJ6AqqzYn/wXPXVSTJo1o9nQML8KU3pmG3sXOqCU
    artifact: nuget-package

  before_build:
    - ps: |  
        . ./build/Write-BuildInfo.ps1
        . ./build/Before-Build.ps1

  build_script:
    - ps: |
        . ./build/Build-Script.ps1
        . ./build/New-NugetPackage.ps1 -Beta

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  test_script:
    - ps: |
        . ./build/Test-Script.ps1

  cache:
    - packages -> **\packages.config


# compile, test, release version to nuget
-
  version: '6.0.0.{build}'
  configuration: Release

  branches:
    only:
      - master

  pull_requests:
    do_not_increment_build_number: true

  nuget:
    project_feed: true

  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  deploy:
    provider: NuGet
    api_key:
      secure: rEqnyErKFkhgxjUgir8i3zftWJ6AqqzYn/wXPXVSTJo1o9nQML8KU3pmG3sXOqCU
    artifact: nuget-package

  before_build:
    - ps: |  
        . ./build/Write-BuildInfo.ps1
        . ./build/Before-Build.ps1

  build_script:
    - ps: |
        . ./build/Build-Script.ps1
        . ./build/New-NugetPackage.ps1
            
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  test_script:
    - ps: |
        . ./build/Test-Script.ps1

  cache:
    - packages -> **\packages.config

