
version: '4.0.0.{build}'
configuration: Release

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

environment:
  feedSource: https://nuget.org/api/v2/
  apiKey:
    secure: TODO-TODO-TODO
  appveyorApiToken:
    secure: TODO-TODO-TODO

init:
  - ps: iex ./appveyor/build-info.ps1
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

before_build:
  - nuget restore Source\NBuilder-NET4.0.sln
  - nuget restore Source\NBuilder-NET3.5.sln
  - nuget restore Source\NBuilder-SL5.sln 

build_script:
  - ps: appveyor\build_script.ps1
  
before_test:
  - ps: . .\appveyor\before_test.ps1
  
on_success:
  - ps: . .\appveyor\on_success.ps1
      
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
test:
  assemblies:
    - 'nbuilder_output\net40\FizzWare.NBuilder.Tests.dll'
    - 'nbuilder_output\net40\FizzWare.NBuilder.FunctionalTests*.dll'

cache:
  - packages -> **\packages.config