
version: '4.0.0.{build}'
configuration: Release

branches:
  only:
    - /release\/.*/

pull_requests:
  do_not_increment_build_number: true

environment:
  feedSource: https://www.myget.org/F/nbuilder/api/v2
  apiKey:
    secure: QTtE0uoegbKLWAsCZdiYU8RD9cVevmVtirTaEqEEBedBPu7A7lSYDQyKrnd6EhYQ
  appveyorApiToken:
    secure: QrKLWAY5+A/JpbuT/l1HsNqSv0b8VL4KFGU3rwZ73Qc=
init:
  - ps: iex ./appveyor/build-info.ps1
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:PackageVersion = "{0}.{1}.{2}-beta-{3}" -f $version.Major, $version.Minor, $version.Build, $version.Revision

before_build:
  - nuget restore Source\NBuilder-NET4.0.sln
  - nuget restore Source\NBuilder-NET3.5.sln
  - nuget restore Source\NBuilder-SL4.sln 

build_script:
  - ps: appveyor\build_script.ps1
  
before_test:
  - ps: . .\appveyor\before_test.ps1
  
on_success:
  - ps: . .\appveyor\on_success.ps1
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

  assemblies:
    - 'nbuilder_output\net40\FizzWare.NBuilder.Tests.dll'
    - 'nbuilder_output\net40\FizzWare.NBuilder.FunctionalTests*.dll'
    - 'nbuilder_output\sl4\FizzWare.NBuilder-Silverlight-4.Tests.dll'

cache:
  - packages -> **\packages.config
